export const GAME_ACTIONS = {
  SET_MATCH: 'SET_MATCH',
  UPDATE_MATCH: 'UPDATE_MATCH',
  SET_PHASE: 'SET_PHASE',
  SET_PLAYERS: 'SET_PLAYERS',
  SELECT_ABILITY: 'SELECT_ABILITY',
  SELECT_TARGET: 'SELECT_TARGET',
  SELECT_VOTE: 'SELECT_VOTE',
  SET_TEMPLATES: 'SET_TEMPLATES',
  ADD_TEMPLATE: 'ADD_TEMPLATE',
  UPDATE_TEMPLATE: 'UPDATE_TEMPLATE',
  REMOVE_TEMPLATE: 'REMOVE_TEMPLATE',
  RESET: 'RESET',
} as const;

export type GameActionType = typeof GAME_ACTIONS[keyof typeof GAME_ACTIONS];
